### ISSUE TITLE
ReadMe中的参数有小错误，另外报错

### ISSUE THREAD

**Issue by su18** [Leezj9671/socialdb_vue_flask#2]
搭建系统为win10，在使用import.py进行测试数据导入时报错
E:\Socialdb\backend>python import.py -f ./test/test.json -d ./test/test.csv
Traceback (most recent call last):
  File "import.py", line 143, in <module>
    main(sys.argv)
  File "import.py", line 136, in main
    file_into_database(data_file, split_sign, csv_sign, regex_pattern, custom_field, ids)
  File "import.py", line 75, in file_into_database
    ef = open(MongoDBConfig.error_line_file, 'a')
AttributeError: type object 'MongoDBConfig' has no attribute 'error_line_file'

-----------------------------------------------------------------------------------------
已自行解决，在config.py中添加以下配置即可
    error_line_file = 'E:\\Socialdb\\backend\\test.log'

**Comment by Leezj9671** [comment]
了解，这个文件我忘了push了，另外还发现一些小问题，更改后你可以再`git pull` 一下
