### ISSUE TITLE
你好，后端无法访问，还有数据是直接从数据库里导么

### ISSUE THREAD

**Issue by z12crypto** [Leezj9671/socialdb_vue_flask#3]
![image](https://user-images.githubusercontent.com/34417521/41807744-0ce5c608-7706-11e8-9fde-a0f7461c9531.png)
![image](https://user-images.githubusercontent.com/34417521/41807750-2e182992-7706-11e8-8e6b-b1832ab962c7.png)

**Comment by Leezj9671** [comment]
后端无法访问主要有两个原因：
1. 前端没有指定`axios`请求的URL;
2. 后端防火墙配置不对，外网无法请求。

数据使用`import.py`从`txt`和`csv`文件导入，使用`-f`指定导入格式。

**Comment by z12crypto** [comment]
![image](https://user-images.githubusercontent.com/34417521/41808095-2df575b4-770b-11e8-858d-b9573a1ef4fc.png)
可是我直接访问也不行，还有麻烦把数据导入方法更新下

**Comment by Leezj9671** [comment]
后端请访问 `http://ip/api/find`，详情请看源代码。
数据导入方法要更新什么？

**Comment by Xiamao12138** [comment]
![image](https://user-images.githubusercontent.com/34417521/41808153-0f8bb93e-770c-11e8-90cc-def4e5f2481e.png)
这个是咋回事0.0

**Comment by z12crypto** [comment]
![image](https://user-images.githubusercontent.com/34417521/41808193-9bdb2b68-770c-11e8-88ca-11f40a532788.png)
请问-d跟-p分别是什么意思。

**Comment by Leezj9671** [comment]
您的截图里面已经写着代表什么意思了，可以看`README`示例。
