### ISSUE TITLE
前端启动失败

### ISSUE THREAD

**Issue by ghost** [Leezj9671/socialdb_vue_flask#4]

**Comment by ghost** [comment]
![picpick 20180911 134842](https://user-images.githubusercontent.com/14077743/45340675-05cad400-b5ca-11e8-94b8-b3299350c345.png)

启动前端的时候出现这样的提示,请问是什么问题呢,可能是文档里没有出现的细节?

**Comment by Leezj9671** [comment]
这种情况可能是我没有正确处理异常导致，后续会改进的。那页面是否能够正常访问？

**Comment by ghost** [comment]
你好,可以访问,但是在输入框内输入内容并回车后,没有任何反应,同时后端没有任何日志输出
ps:还没有导入库,不过应该不是问题所在吧?

**Comment by Leezj9671** [comment]
应该是交互出现了错误，我并没有复现到该问题。你可以尝试抓包看有没有正确发出请求，有没有收到回复，可以将抓包截图发给我看看。
